export enum RootPath {
  class = 'class',
  countries = 'countries',
  courses = 'courses',
  degrees = 'degrees',
  login = 'login',
  logout = 'logout',
  message = 'message',
  profile = 'profile',
  signUp = 'signup',
  statistics = 'statistics',
  student = 'student',
  students = 'students',
  teachers = 'teachers',
  userRole = 'userRole',
}