import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout, Menu, message } from 'antd';
import Router, { useRouter } from 'next/router';

const { Header, Content, Footer } = Layout;

const Home: NextPage = () => {
  const axios = require('axios').default;
  const router = useRouter();
  const handleClick = () => {
    axios.post('http://cms.chtoma.com/api/logout')
      .then((result: any) => {
        const data = result.data.data;
        localStorage.setItem('cms', JSON.stringify(data))
        router.push('/')
      }).catch((error: any) => {
        const data = error.data;
        localStorage.setItem('cms', JSON.stringify(data))
        router.push('/')
        // message.error('Please input right pwd')
      });
  }
  return (
    <Layout className="layout">

      <Head>
        <title>CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header style={{ position: 'fixed', zIndex: 1, width: '100%' }}>
        <div className="logo" defaultValue="CMS" />
        <Menu
          theme="dark"
          mode="horizontal"
        >
          <Menu.Item>item</Menu.Item>
          <Menu.Item>item</Menu.Item>
          <Menu.Item>item</Menu.Item>
          <Menu.Item>item</Menu.Item>
          <Menu.Item>item</Menu.Item>
          <Menu.Item onClick={handleClick}>LOG OUT</Menu.Item>
        </Menu>
      </Header>

      <Content className="site-layout" style={{ padding: '0 50px', marginTop: 64 }}>
        <div className="site-layout-background" style={{ padding: 24, minHeight: 380 }}>
        </div>
      </Content>
      <Footer style={{ textAlign: 'center' }}>©2022</Footer>

    </Layout>
  )
}

export default Home
